services:
  - type: web
    name: ticketsbot-api-bot
    runtime: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    repo: https://github.com/maydotinc/ticketsbot-ai.git
    branch: main
    region: oregon
    plan: starter
    autoDeploy: true
    healthCheckPath: /health
    numInstances: 1
    dockerCommand: |
      bash -c "pnpm db:push && npx concurrently -n api,bot -c blue,green 'pnpm --filter @ticketsbot/api start' 'pnpm --filter @ticketsbot/bot start'"

    envVars:
      - fromGroup: ticketsbot-env
      - key: NODE_ENV
        value: production

envVarGroups:
  - name: ticketsbot-env
    envVars:
      # Core secrets (fill these in Render dashboard)
      - key: DATABASE_URL
        value: ""
      - key: BETTER_AUTH_SECRET
        value: ""
      - key: DISCORD_TOKEN
        value: ""
      - key: DISCORD_CLIENT_ID
        value: ""
      - key: DISCORD_CLIENT_SECRET
        value: ""

      # Service URLs (update these with your actual URLs)
      - key: WEB_URL
        value: "https://your-app.vercel.app"
      - key: API_URL
        value: "https://your-app.onrender.com"

      # Optional services
      - key: REDIS_URL
        value: ""
