services:
  - type: web
    name: ticketsbot-api-bot
    runtime: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    repo: https://github.com/maydotinc/ticketsbot-ai.git
    branch: main
    region: oregon
    plan: starter
    autoDeploy: true
    healthCheckPath: /health
    numInstances: 1
    dockerCommand: |
      bash -c "pnpm db:push && npx concurrently -n api,bot -c blue,green 'pnpm --filter @ticketsbot/api start' 'pnpm --filter @ticketsbot/bot start'"

    envVars:
      - fromGroup: ticketsbot-core
      - fromGroup: ticketsbot-secrets
      - key: NODE_ENV
        value: production

envVarGroups:
  - name: ticketsbot-core
    envVars:
      - key: API_PORT
        value: "3001"
      - key: BOT_PORT
        value: "3002"
      - key: BASE_DOMAIN
        value: "ticketsbot.dev"
      - key: WEB_URL
        value: "https://ticketsbot.vercel.app"
      - key: API_URL
        value: "https://ticketsbot-api-bot.onrender.com"
      - key: DISCORD_REDIRECT_URI
        value: "https://ticketsbot-api-bot.onrender.com/auth/callback/discord"

  - name: ticketsbot-secrets
    envVars:
      - key: DATABASE_URL
        value: ""
      - key: REDIS_URL
        value: ""
      - key: DISCORD_TOKEN
        value: ""
      - key: DISCORD_CLIENT_ID
        value: ""
      - key: DISCORD_CLIENT_SECRET
        value: ""
      - key: BETTER_AUTH_SECRET
        value: ""