import {
  createTag,
  deleteTag,
  ensureDiscordUser,
  getDiscordUser,
  ensureGuild,
  getGuildById,
  getTag,
  listTags,
  updateGuild,
  updateTag,
  ensureGuildWithDefaults,
  getGuildSettings,
  syncGuildBotInstalledStatus,
  checkGuildBlacklistEntry,
  toggleGuildBlacklistEntry,
  hasOpenTickets,
  getCountByStatus,
  removeParticipantFromAll,
  getPanelById,
  getPanelGuildId,
  getTicketByChannelId,
  isTicketChannel,
  getByIdUnchecked,
  getByIds,
} from "./operations";

export const db = {
  discordUser: {
    ensure: ensureDiscordUser,
    get: getDiscordUser,
  },
  guild: {
    ensure: ensureGuild,
    ensureWithDefaults: ensureGuildWithDefaults,
    get: getGuildById,
    update: updateGuild,
    syncBotInstalledStatus: syncGuildBotInstalledStatus,
    getSettings: getGuildSettings,
    toggleBlacklistEntry: toggleGuildBlacklistEntry,
    checkBlacklistEntry: checkGuildBlacklistEntry,
  },
  panel: {
    get: getPanelById,
    getGuildId: getPanelGuildId,
  },
  tag: {
    create: createTag,
    delete: deleteTag,
    get: getTag,
    list: listTags,
    update: updateTag,
  },
  ticket: {
    get: getTicketByChannelId,
    getByIdUnchecked: getByIdUnchecked,
    getByIds: getByIds,
    getCountByStatus: getCountByStatus,
    hasOpenTickets: hasOpenTickets,
    removeParticipantFromAll: removeParticipantFromAll,
    isTicketChannel: isTicketChannel,
  },
};
