import {
  createTag,
  deleteTag,
  ensureDiscordUser,
  getDiscordUser,
  getTag,
  listTags,
  updateTag,
  hasOpenTickets,
  getCountByStatus,
  removeParticipantFromAll,
  getPanelById,
  getPanelGuildId,
  getPanelWithForm,
  listPanelsByGuildId,
  createPanel,
  updatePanel,
  deletePanel,
  deployPanel,
  getTicketByChannelId,
  isTicketChannel,
  getByIdUnchecked,
  getByIds,
  getById as getTicketById,
  getUserOpenCount,
  addParticipant,
  removeParticipant,
  updateChannelId,
  list as listTickets,
  update as updateTicket,
} from "./operations";
import {
  getGuildById,
  updateGuild,
  getGuildSettings,
  getTeamRoles,
} from "./operations/guild/queries";
import {
  ensureGuild,
  ensureGuildWithDefaults,
  syncGuildBotInstalledStatus,
  checkGuildBlacklistEntry,
  toggleGuildBlacklistEntry,
  updateGuildSettings,
} from "./operations/guild/mutations";

import { getActiveMembersForRole } from "./operations/role";

export const db = {
  discordUser: {
    ensure: ensureDiscordUser,
    get: getDiscordUser,
  },
  guild: {
    ensure: ensureGuild,
    ensureWithDefaults: ensureGuildWithDefaults,
    get: getGuildById,
    update: updateGuild,
    updateSettings: updateGuildSettings,
    syncBotInstalledStatus: syncGuildBotInstalledStatus,
    getSettings: getGuildSettings,
    toggleBlacklistEntry: toggleGuildBlacklistEntry,
    checkBlacklistEntry: checkGuildBlacklistEntry,
    getTeamRoles: getTeamRoles,
  },
  panel: {
    get: getPanelById,
    getById: getPanelById,
    getGuildId: getPanelGuildId,
    getWithForm: getPanelWithForm,
    list: listPanelsByGuildId,
    listByGuildId: listPanelsByGuildId,
    create: createPanel,
    update: updatePanel,
    remove: deletePanel,
    deploy: deployPanel,
  },
  role: {
    getActiveMembers: getActiveMembersForRole,
  },
  tag: {
    create: createTag,
    delete: deleteTag,
    get: getTag,
    list: listTags,
    update: updateTag,
  },
  ticket: {
    get: getTicketByChannelId,
    getById: getTicketById,
    getByIdUnchecked: getByIdUnchecked,
    getByIds: getByIds,
    list: listTickets,
    update: updateTicket,
    getCountByStatus: getCountByStatus,
    hasOpenTickets: hasOpenTickets,
    getUserOpenCount: getUserOpenCount,
    addParticipant: addParticipant,
    removeParticipant: removeParticipant,
    removeParticipantFromAll: removeParticipantFromAll,
    updateChannelId: updateChannelId,
    isTicketChannel: isTicketChannel,
  },
};
