name: TypeScript Quality

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  typescript-quality:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.11.1

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run TypeScript type checking
        run: pnpm typecheck

      - name: Run ESLint with zero warnings
        run: pnpm lint

      - name: Check for barrel exports
        run: |
          echo "Checking for barrel exports..."
          if grep -r "export \* from" packages/ apps/ --include="index.ts" --exclude-dir=node_modules --exclude-dir=dist; then
            echo "❌ Found barrel exports! These should be eliminated."
            exit 1
          else
            echo "✅ No barrel exports found"
          fi

      - name: Check for explicit 'any' types
        run: |
          echo "Checking for explicit 'any' types..."
          ANY_COUNT=$(grep -r ": any" packages/ apps/ --include="*.ts" --include="*.tsx" --exclude-dir=node_modules --exclude-dir=dist --exclude-dir=tests | wc -l)
          echo "Found $ANY_COUNT explicit 'any' types"
          if [ $ANY_COUNT -gt 150 ]; then
            echo "❌ Too many explicit 'any' types (limit: 150, found: $ANY_COUNT)"
            exit 1
          else
            echo "✅ Explicit 'any' types within acceptable limit"
          fi

      - name: Run tests
        run: pnpm test

  type-coverage:
    runs-on: ubuntu-latest
    needs: typescript-quality

    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.11.1

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Generate type coverage report
        run: |
          echo "## TypeScript Quality Report" > type-coverage.md
          echo "" >> type-coverage.md
          echo "### ESLint Status" >> type-coverage.md
          echo "✅ Zero warnings policy enforced" >> type-coverage.md
          echo "" >> type-coverage.md
          echo "### Barrel Exports" >> type-coverage.md
          echo "✅ No barrel exports allowed" >> type-coverage.md
          echo "" >> type-coverage.md
          echo "### Explicit 'any' Types" >> type-coverage.md
          ANY_COUNT=$(grep -r ": any" packages/ apps/ --include="*.ts" --include="*.tsx" --exclude-dir=node_modules --exclude-dir=dist --exclude-dir=tests | wc -l)
          echo "Current count: $ANY_COUNT / 150 (limit)" >> type-coverage.md

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: type-coverage-report
          path: type-coverage.md
