name: TypeScript Type Check

on:
  push:
    branches:
      - main
      - develop
      - "feature/**"
      - "bot-framework"
  pull_request:
    branches:
      - main
      - develop

jobs:
  typecheck:
    name: Type Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 10.11.1

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Setup test environment
        run: |
          # Create minimal .env for typecheck
          cat > .env << EOF
          NODE_ENV=test
          TURBO_ENV=dev
          DATABASE_URL=postgresql://test:test@localhost:5432/test
          WEB_PORT=3000
          API_PORT=3001
          BOT_PORT=3002
          WEB_URL=http://localhost:3000
          API_URL=http://localhost:3001
          NEXT_PUBLIC_API_URL=http://localhost:3001
          DISCORD_CLIENT_ID=test
          DISCORD_CLIENT_SECRET=test
          DISCORD_TOKEN=test
          DISCORD_REDIRECT_URI=http://localhost:3001/auth/callback/discord
          BETTER_AUTH_SECRET=test_secret_must_be_at_least_32_characters_long
          EOF

      - name: Generate Prisma Client
        run: pnpm --filter @ticketsbot/core db:generate

      - name: Run TypeScript type check
        run: pnpm typecheck

      - name: Check @ticketsbot/discord specifically
        run: pnpm typecheck:discord

  discord-package-test:
    name: Discord Package Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 10.11.1

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run @ticketsbot/discord tests
        run: pnpm test:discord
        continue-on-error: true # Tests have issues currently

      - name: Build @ticketsbot/discord
        run: pnpm --filter @ticketsbot/discord build
